# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numar_total_de_caractere', models.IntegerField(default=0)),
                ('Numar_de_cifre', models.IntegerField(default=0)),
                ('Numar_caractere_speciale', models.IntegerField(default=0)),
            ],
        ),
    ]
